server:
  port: 9000

spring:
  application:
    name: membership-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/payment}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

axon:
  axonserver:
    enabled: false
  eventhandling:
    processors:
      default:
        mode: subscribing
  serializer:
    general: jackson
    events: jackson
    messages: jackson

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.jh.membershipservice
  paths-to-match: /**
  info:
    title: Membership Service API
    description: Payment System - Membership Service API
    version: 1.0.0
