server:
  port: 9000

spring:
  application:
    name: membership-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/payment}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

axon:
  axonserver:
    enabled: false
  eventhandling:
    processors:
      default:
        mode: subscribing
  serializer:
    general: jackson
    events: jackson
    messages: jackson
